# This format is suitable for the following services
#   - get_err_warn_code
#   - get_linear_motor_sco  # The old name is get_linear_track_sco, please use the new one

---

int16 ret
string message

int16[] datas
