# This format is suitable for the following services
#   - set_mode
#   - set_state
#   - set_collision_sensitivity
#   - set_teach_sensitivity
#   - set_gripper_mode
#   - set_gripper_enable
#   - set_bio_gripper_speed
#   - set_fence_mode
#   - set_reduced_mode
#   - set_self_collision_detection
#   - set_simulation_robot
#   - set_baud_checkset_enable
#   - set_report_tau_or_i
#   - set_ft_sensor_enable      # The old name is ft_sensor_enable, please use the new one
#   - set_ft_sensor_mode        # The old name is ft_sensor_app_set, please use the new one
#   - set_linear_motor_enable   # The old name is set_linear_track_enable, please use the new one
#   - set_linear_motor_speed    # The old name is set_linear_track_speed, please use the new one
#   - set_cartesian_velo_continuous
#   - set_allow_approx_motion
#   - set_only_check_type
#   - config_tgpio_reset_when_stop
#   - config_cgpio_reset_when_stop

int16 data

---

int16 ret
string message